### PR TITLE
Various Breaking Cleanups

### PR DESCRIPTION
**Pull request by mcordingley**
This PR is a grab-bag of improvements to code quality. If you object to specific changes, you may wish to cherry-pick commits. The notable changes are:

- I removed all mention of the back-end from the key provider. The key providers had no reason to know about the back-end in use, but its presence meant an additional method on the interface and somewhat more complicated instantiation logic. This change made the back-end a required parameter to the `CipherSweet` constructor, but the additional effort of providing it there is (more than) offset by no longer having to provide it to a key provider.
- I removed `getDefaultBackend()`, as a change in the environment could cause a change in back-end, thereby rendering indexes and encrypted values "invalid". Different environments with the same code could nonetheless try to run different back-ends. :beetle: 
- I updated the `CipherSweet` constructor to make the back-end again an optional parameter. If not provided, we fall back to a default back-end. Unlike the removed factory method, this will always choose the same back-end implementation. Unless the user has specific reason otherwise, this is the back-end they will want. If the environment is unable to accommodate `ModernCrypto`, attempting to use it should throw an error and prompt either a code change or the installation of libsodium. Either way, the choice made will be explicit and intentional.
- I reduced some repeated logic in the tests that was bothering me.

### CODE REVIEW

**Comment by mcordingley** [comment]
One more change:

- Removed `ArrayProvider`. It doesn't seem to add anything beyond what `StringProvider` already gives, but is less direct about it.

**Comment by mcordingley** [comment]
Wasn't expecting this to merge so quickly! If you're prepping for a 2.0 release and targeting PHP 7.1 (was it?) do you mind waiting a day or two before release so I can pepper type hints throughout the code and `final`ize any classes not meant for extension?

**Comment by paragonie-scott** [comment]
I'm not bumping the major PHP version in v2, just introduced some other changes I wanted to make.

A PHP version bump can land in v3.x, if desired.

**Comment by mcordingley** [comment]
Works for me. :+1:

**Comment by paragonie-scott** [comment]
To explain the PHP version issue: This library was originally developed with the intention of replacing Blowfish in SugarCRM/SuiteCRM/etc. which supported PHP 5.5 at the time but today only support PHP 5.6.

Although the scope of CipherSweet has widened significantly since I wrote the first prototype, I don't wish to lock people out who are using it for its original intended purpose. That's why I didn't proceed with a PHP version bump yet.

If you want to kick v3 support all the way up to PHP 7.2 or higher, I'm fine with that too.

**Comment by mcordingley** [comment]
Sure thing. I was thinking that if you were going to do so now, I'd better push those changes in before it got too late. But since you're not bumping, there's no rush. I'll switch gears back to the Eloquent integration soon as I get another moment.

**Comment by paragonie-scott** [comment]
Awesome: 👍

**Pull request merged**
