### PR TITLE
docs/internals: Correct Hamming distance

### PR DESCRIPTION
**Pull request by KellerFuchs**

### CODE REVIEW

**Comment by KellerFuchs** [comment]
@paragonie-scott Also consider explaining why the Hamming distance is relevant for domain separation?  ;)

**Comment by paragonie-scott** [comment]
Sure, but I'll need to dig into the attacks against modified HMAC first.

**Comment by KellerFuchs** [comment]
@paragonie-scott Should this be merged and an issue opened for explaining the domain separation bits?

**Comment by paragonie-scott** [comment]
Yep, I think that's a good next move.

**Pull request merged**
